export interface DividendStock {
  ticker: string;
  price: number;
  annualDividend: number;
  yield: number;
  dripEligible: boolean;
  months: string[];
  sector: string;
  ottoScore: number;
  payoutRatio: number;
  insight?: string;
}

export const mockDividendStocks: DividendStock[] = [
  // Original 3
  {
    ticker: 'AAPL',
    price: 175.0,
    annualDividend: 0.92,
    yield: 0.53,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Technology',
    ottoScore: 87,
    payoutRatio: 25,
    insight: 'Growth tech stock with stable dividend.',
  },
  {
    ticker: 'JNJ',
    price: 165.0,
    annualDividend: 4.76,
    yield: 2.88,
    dripEligible: true,
    months: ['Mar', 'Jun', 'Sep', 'Dec'],
    sector: 'Healthcare',
    ottoScore: 91,
    payoutRatio: 48,
    insight: 'Blue chip with strong dividend history.',
  },
  {
    ticker: 'KO',
    price: 60.0,
    annualDividend: 1.84,
    yield: 3.07,
    dripEligible: true,
    months: ['Jan', 'Apr', 'Jul', 'Oct'],
    sector: 'Consumer Staples',
    ottoScore: 85,
    payoutRatio: 75,
    insight: 'High yield stable income stock.',
  },

  // Additional companies
  {
    ticker: 'PG',
    price: 145.0,
    annualDividend: 3.65,
    yield: 2.52,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Consumer Staples',
    ottoScore: 88,
    payoutRatio: 60,
    insight: 'Defensive stock with consistent payouts.',
  },
  {
    ticker: 'MSFT',
    price: 315.0,
    annualDividend: 2.72,
    yield: 0.86,
    dripEligible: true,
    months: ['Mar', 'Jun', 'Sep', 'Dec'],
    sector: 'Technology',
    ottoScore: 93,
    payoutRatio: 28,
    insight: 'Leading cloud business with growing yield.',
  },
  {
    ticker: 'T',
    price: 17.0,
    annualDividend: 1.11,
    yield: 6.53,
    dripEligible: false,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Telecommunications',
    ottoScore: 76,
    payoutRatio: 70,
    insight: 'High yield telecom, payout under pressure.',
  },
  {
    ticker: 'VZ',
    price: 37.0,
    annualDividend: 1.53,
    yield: 4.14,
    dripEligible: false,
    months: ['Mar', 'Jun', 'Sep', 'Dec'],
    sector: 'Telecommunications',
    ottoScore: 78,
    payoutRatio: 60,
    insight: 'Stable but revenue slowing.',
  },
  {
    ticker: 'XOM',
    price: 105.0,
    annualDividend: 4.00,
    yield: 3.81,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Energy',
    ottoScore: 82,
    payoutRatio: 55,
    insight: 'Oil major with solid dividend yield.',
  },
  {
    ticker: 'CVX',
    price: 160.0,
    annualDividend: 5.36,
    yield: 3.35,
    dripEligible: true,
    months: ['Mar', 'Jun', 'Sep', 'Dec'],
    sector: 'Energy',
    ottoScore: 84,
    payoutRatio: 60,
    insight: 'Global energy player with consistent dividends.',
  },
  {
    ticker: 'PFE',
    price: 42.0,
    annualDividend: 1.65,
    yield: 3.93,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Healthcare',
    ottoScore: 86,
    payoutRatio: 45,
    insight: 'Pharma with steady dividend growth.',
  },
  {
    ticker: 'MRK',
    price: 85.0,
    annualDividend: 3.00,
    yield: 3.53,
    dripEligible: true,
    months: ['Jan', 'Apr', 'Jul', 'Oct'],
    sector: 'Healthcare',
    ottoScore: 89,
    payoutRatio: 55,
    insight: 'Diversified pipeline supports dividend.',
  },
  {
    ticker: 'WMT',
    price: 150.0,
    annualDividend: 2.24,
    yield: 1.49,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Consumer Staples',
    ottoScore: 88,
    payoutRatio: 30,
    insight: 'Retail giant with stable cash flow.',
  },
  {
    ticker: 'HD',
    price: 310.0,
    annualDividend: 7.20,
    yield: 2.32,
    dripEligible: true,
    months: ['Mar', 'Jun', 'Sep', 'Dec'],
    sector: 'Consumer Discretionary',
    ottoScore: 90,
    payoutRatio: 55,
    insight: 'Home improvement leader with steady dividend.',
  },
  {
    ticker: 'MO',
    price: 52.0,
    annualDividend: 3.84,
    yield: 7.38,
    dripEligible: false,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Consumer Staples',
    ottoScore: 79,
    payoutRatio: 80,
    insight: 'Tobacco stock with very high yield.',
  },
  {
    ticker: 'IBM',
    price: 135.0,
    annualDividend: 6.60,
    yield: 4.89,
    dripEligible: true,
    months: ['Mar', 'Jun', 'Sep', 'Dec'],
    sector: 'Technology',
    ottoScore: 81,
    payoutRatio: 50,
    insight: 'Legacy tech paying strong dividend.',
  },
  {
    ticker: 'CVS',
    price: 70.0,
    annualDividend: 2.00,
    yield: 2.86,
    dripEligible: true,
    months: ['Jan', 'Apr', 'Jul', 'Oct'],
    sector: 'Healthcare',
    ottoScore: 83,
    payoutRatio: 40,
    insight: 'Retail pharmacy with steady dividend.',
  },
  {
    ticker: 'PEP',
    price: 190.0,
    annualDividend: 5.04,
    yield: 2.65,
    dripEligible: true,
    months: ['Jan', 'Apr', 'Jul', 'Oct'],
    sector: 'Consumer Staples',
    ottoScore: 92,
    payoutRatio: 60,
    insight: 'Beverages giant with consistent growth.',
  },
  {
    ticker: 'MMM',
    price: 155.0,
    annualDividend: 6.12,
    yield: 3.95,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Industrials',
    ottoScore: 80,
    payoutRatio: 75,
    insight: 'Industrial conglomerate with high dividend.',
  },
  {
    ticker: 'UTX',
    price: 120.0,
    annualDividend: 2.64,
    yield: 2.20,
    dripEligible: true,
    months: ['Mar', 'Jun', 'Sep', 'Dec'],
    sector: 'Industrials',
    ottoScore: 84,
    payoutRatio: 50,
    insight: 'Aerospace/defense with stable payout.',
  },
  {
    ticker: 'PG&E',
    price: 12.0,
    annualDividend: 0.47,
    yield: 3.92,
    dripEligible: true,
    months: ['Mar', 'Jun', 'Sep', 'Dec'],
    sector: 'Utilities',
    ottoScore: 68,
    payoutRatio: 70,
    insight: 'Regulated utility with mid-tier yield.',
  },
  {
    ticker: 'NEE',
    price: 75.0,
    annualDividend: 3.50,
    yield: 4.67,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Utilities',
    ottoScore: 86,
    payoutRatio: 65,
    insight: 'Renewable-heavy utility asset.',
  },
  {
    ticker: 'ABBV',
    price: 160.0,
    annualDividend: 6.16,
    yield: 3.85,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Healthcare',
    ottoScore: 87,
    payoutRatio: 45,
    insight: 'Strong pharma div with growing yield.',
  },
  {
    ticker: 'COST',
    price: 540.0,
    annualDividend: 4.80,
    yield: 0.89,
    dripEligible: true,
    months: ['Jan', 'Apr', 'Jul', 'Oct'],
    sector: 'Consumer Staples',
    ottoScore: 94,
    payoutRatio: 25,
    insight: 'Discount retailer with minimal payout.',
  },
  {
    ticker: 'INTC',
    price: 33.0,
    annualDividend: 1.44,
    yield: 4.36,
    dripEligible: true,
    months: ['Mar', 'Jun', 'Sep', 'Dec'],
    sector: 'Technology',
    ottoScore: 75,
    payoutRatio: 45,
    insight: 'Legacy chipmaker cycling through challenges.',
  },
  {
    ticker: 'ORCL',
    price: 105.0,
    annualDividend: 1.44,
    yield: 1.37,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Technology',
    ottoScore: 88,
    payoutRatio: 30,
    insight: 'Enterprise software plus cloud with dividend growth.',
  },
  {
    ticker: 'BP',
    price: 28.0,
    annualDividend: 1.65,
    yield: 5.89,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Energy',
    ottoScore: 79,
    payoutRatio: 60,
    insight: 'International oil major with high yield.',
  },
  {
    ticker: 'LTC',
    price: 180.0,
    annualDividend: 5.76,
    yield: 3.20,
    dripEligible: true,
    months: ['Feb', 'May', 'Aug', 'Nov'],
    sector: 'Financials',
    ottoScore: 83,
    payoutRatio: 50,
    insight: 'Insurer offering decent yield in finance.',
  },
];